2025-05-30 22:16:53.867 | INFO     | utils.local_interpreter:initialize:33 - 初始化本地内核
2025-05-30 22:16:54.664 | INFO     | utils.local_interpreter:execute_code_:141 - 执行代码: import os
work_dir = r'./test_case/o4'
os.makedirs(work_dir, exist_ok=True)
os.chdir(work_dir)
print('当前工作目录:', os.getcwd())
import matplotlib.pyplot as plt
import matplotlib as mpl
plt.rcParams['font.sans-serif'] = ['Arial Unicode MS', 'SimHei', 'Microsoft YaHei', 'WenQuanYi Micro Hei', 'PingFang SC', 'Hiragino Sans GB', 'Heiti SC', 'DejaVu Sans', 'sans-serif']
plt.rcParams['axes.unicode_minus'] = False
plt.rcParams['font.family'] = 'sans-serif'
mpl.rcParams['font.size'] = 12
mpl.rcParams['axes.labelsize'] = 12
mpl.rcParams['xtick.labelsize'] = 10
mpl.rcParams['ytick.labelsize'] = 10

2025-05-30 22:17:45.481 | INFO     | utils.local_interpreter:execute_code:61 - 执行代码: print('111')
2025-05-30 22:17:45.485 | INFO     | utils.local_interpreter:execute_code:75 - 开始在本地执行代码...
2025-05-30 22:17:45.486 | INFO     | utils.local_interpreter:execute_code_:141 - 执行代码: print('111')
2025-05-30 22:17:45.494 | INFO     | utils.local_interpreter:execute_code:78 - 代码执行完成，开始处理结果...
2025-05-30 22:17:45.504 | INFO     | utils.local_interpreter:execute_code:128 - text_to_gpt: ['[stdout]\n111\n']
2025-05-30 22:18:37.035 | INFO     | utils.local_interpreter:execute_code:61 - 执行代码: print('111')
2025-05-30 22:18:37.039 | INFO     | utils.local_interpreter:execute_code:75 - 开始在本地执行代码...
2025-05-30 22:18:37.040 | INFO     | utils.local_interpreter:execute_code_:141 - 执行代码: print('111')
2025-05-30 22:18:37.049 | INFO     | utils.local_interpreter:execute_code:78 - 代码执行完成，开始处理结果...
2025-05-30 22:18:37.062 | INFO     | utils.local_interpreter:execute_code:128 - text_to_gpt: ['[stdout]\n111\n']
2025-05-30 22:18:37.063 | INFO     | utils.local_interpreter:cleanup:218 - 关闭内核
2025-05-30 22:19:21.637 | INFO     | utils.local_interpreter:execute_code:61 - 执行代码: print('111')
2025-05-30 22:19:21.643 | INFO     | utils.local_interpreter:execute_code:75 - 开始在本地执行代码...
2025-05-30 22:19:21.643 | INFO     | utils.local_interpreter:execute_code_:141 - 执行代码: print('111')
2025-05-30 22:19:21.649 | INFO     | utils.local_interpreter:execute_code:78 - 代码执行完成，开始处理结果...
2025-05-30 22:19:21.649 | INFO     | utils.local_interpreter:execute_code:128 - text_to_gpt: []
2025-05-30 22:19:54.645 | INFO     | utils.local_interpreter:initialize:33 - 初始化本地内核
2025-05-30 22:19:55.315 | INFO     | utils.local_interpreter:execute_code_:141 - 执行代码: import os
work_dir = r'./test_case/o4'
os.makedirs(work_dir, exist_ok=True)
os.chdir(work_dir)
print('当前工作目录:', os.getcwd())
import matplotlib.pyplot as plt
import matplotlib as mpl
plt.rcParams['font.sans-serif'] = ['Arial Unicode MS', 'SimHei', 'Microsoft YaHei', 'WenQuanYi Micro Hei', 'PingFang SC', 'Hiragino Sans GB', 'Heiti SC', 'DejaVu Sans', 'sans-serif']
plt.rcParams['axes.unicode_minus'] = False
plt.rcParams['font.family'] = 'sans-serif'
mpl.rcParams['font.size'] = 12
mpl.rcParams['axes.labelsize'] = 12
mpl.rcParams['xtick.labelsize'] = 10
mpl.rcParams['ytick.labelsize'] = 10

2025-05-30 22:20:32.744 | INFO     | utils.local_interpreter:execute_code:61 - 执行代码: from developer.prompt import get_developer
2025-05-30 22:20:32.748 | INFO     | utils.local_interpreter:execute_code:75 - 开始在本地执行代码...
2025-05-30 22:20:32.750 | INFO     | utils.local_interpreter:execute_code_:141 - 执行代码: from developer.prompt import get_developer
2025-05-30 22:20:32.929 | INFO     | utils.local_interpreter:execute_code:78 - 代码执行完成，开始处理结果...
2025-05-30 22:20:32.929 | ERROR    | utils.local_interpreter:execute_code:122 - 执行错误: ---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[2], line 1
----> 1 from developer.prompt import get_developer

ModuleNotFoundError: No module named 'developer'
2025-05-30 22:20:32.933 | INFO     | utils.local_interpreter:execute_code:128 - text_to_gpt: ["---------------------------------------------------------------------------\nModuleNotFoundError                       Traceback (most recent call last)\nCell In[2], line 1\n----> 1 from developer.prompt import get_developer\n\nModuleNotFoundError: No module named 'developer'"]
2025-05-30 22:23:50.533 | INFO     | utils.local_interpreter:execute_code:61 - 执行代码: from api import gpt_chat
2025-05-30 22:23:50.536 | INFO     | utils.local_interpreter:execute_code:75 - 开始在本地执行代码...
2025-05-30 22:23:50.536 | INFO     | utils.local_interpreter:execute_code_:141 - 执行代码: from api import gpt_chat
2025-05-30 22:23:50.558 | INFO     | utils.local_interpreter:execute_code:78 - 代码执行完成，开始处理结果...
2025-05-30 22:23:50.558 | ERROR    | utils.local_interpreter:execute_code:122 - 执行错误: ---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[3], line 1
----> 1 from api import gpt_chat

ModuleNotFoundError: No module named 'api'
2025-05-30 22:23:50.561 | INFO     | utils.local_interpreter:execute_code:128 - text_to_gpt: ["---------------------------------------------------------------------------\nModuleNotFoundError                       Traceback (most recent call last)\nCell In[3], line 1\n----> 1 from api import gpt_chat\n\nModuleNotFoundError: No module named 'api'"]
2025-05-30 22:27:36.657 | INFO     | utils.local_interpreter:initialize:33 - 初始化本地内核
2025-05-30 22:27:37.240 | INFO     | utils.local_interpreter:execute_code_:141 - 执行代码: import os
work_dir = r'./test_case/o4'
os.makedirs(work_dir, exist_ok=True)
os.chdir(work_dir)
print('当前工作目录:', os.getcwd())
import matplotlib.pyplot as plt
import matplotlib as mpl
plt.rcParams['font.sans-serif'] = ['Arial Unicode MS', 'SimHei', 'Microsoft YaHei', 'WenQuanYi Micro Hei', 'PingFang SC', 'Hiragino Sans GB', 'Heiti SC', 'DejaVu Sans', 'sans-serif']
plt.rcParams['axes.unicode_minus'] = False
plt.rcParams['font.family'] = 'sans-serif'
mpl.rcParams['font.size'] = 12
mpl.rcParams['axes.labelsize'] = 12
mpl.rcParams['xtick.labelsize'] = 10
mpl.rcParams['ytick.labelsize'] = 10

2025-05-30 22:27:38.866 | INFO     | utils.local_interpreter:execute_code:61 - 执行代码: from api import gpt_chat
2025-05-30 22:27:38.869 | INFO     | utils.local_interpreter:execute_code:75 - 开始在本地执行代码...
2025-05-30 22:27:38.870 | INFO     | utils.local_interpreter:execute_code_:141 - 执行代码: from api import gpt_chat
2025-05-30 22:27:39.048 | INFO     | utils.local_interpreter:execute_code:78 - 代码执行完成，开始处理结果...
2025-05-30 22:27:39.048 | ERROR    | utils.local_interpreter:execute_code:122 - 执行错误: ---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[2], line 1
----> 1 from api import gpt_chat

ModuleNotFoundError: No module named 'api'
2025-05-30 22:27:39.051 | INFO     | utils.local_interpreter:execute_code:128 - text_to_gpt: ["---------------------------------------------------------------------------\nModuleNotFoundError                       Traceback (most recent call last)\nCell In[2], line 1\n----> 1 from api import gpt_chat\n\nModuleNotFoundError: No module named 'api'"]
2025-05-30 22:28:18.906 | INFO     | utils.local_interpreter:initialize:33 - 初始化本地内核
2025-05-30 22:28:19.706 | INFO     | utils.local_interpreter:execute_code_:141 - 执行代码: import os
work_dir = r'./test_case/o4'
os.makedirs(work_dir, exist_ok=True)
os.chdir(work_dir)
print('当前工作目录:', os.getcwd())
import matplotlib.pyplot as plt
import matplotlib as mpl
plt.rcParams['font.sans-serif'] = ['Arial Unicode MS', 'SimHei', 'Microsoft YaHei', 'WenQuanYi Micro Hei', 'PingFang SC', 'Hiragino Sans GB', 'Heiti SC', 'DejaVu Sans', 'sans-serif']
plt.rcParams['axes.unicode_minus'] = False
plt.rcParams['font.family'] = 'sans-serif'
mpl.rcParams['font.size'] = 12
mpl.rcParams['axes.labelsize'] = 12
mpl.rcParams['xtick.labelsize'] = 10
mpl.rcParams['ytick.labelsize'] = 10

2025-05-30 22:28:21.723 | INFO     | utils.local_interpreter:execute_code:61 - 执行代码: from api import gpt_chat
2025-05-30 22:28:21.729 | INFO     | utils.local_interpreter:execute_code:75 - 开始在本地执行代码...
2025-05-30 22:28:21.731 | INFO     | utils.local_interpreter:execute_code_:141 - 执行代码: from api import gpt_chat
2025-05-30 22:28:21.904 | INFO     | utils.local_interpreter:execute_code:78 - 代码执行完成，开始处理结果...
2025-05-30 22:28:21.905 | ERROR    | utils.local_interpreter:execute_code:122 - 执行错误: ---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[2], line 1
----> 1 from api import gpt_chat

ModuleNotFoundError: No module named 'api'
2025-05-30 22:28:21.909 | INFO     | utils.local_interpreter:execute_code:128 - text_to_gpt: ["---------------------------------------------------------------------------\nModuleNotFoundError                       Traceback (most recent call last)\nCell In[2], line 1\n----> 1 from api import gpt_chat\n\nModuleNotFoundError: No module named 'api'"]
2025-05-30 22:29:32.509 | INFO     | utils.local_interpreter:execute_code:61 - 执行代码: 
import os, sys
print("Current Working Directory:", os.getcwd())
print("sys.path:", sys.path)

2025-05-30 22:29:32.513 | INFO     | utils.local_interpreter:execute_code:75 - 开始在本地执行代码...
2025-05-30 22:29:32.515 | INFO     | utils.local_interpreter:execute_code_:141 - 执行代码: 
import os, sys
print("Current Working Directory:", os.getcwd())
print("sys.path:", sys.path)

2025-05-30 22:29:32.524 | INFO     | utils.local_interpreter:execute_code:78 - 代码执行完成，开始处理结果...
2025-05-30 22:29:32.536 | INFO     | utils.local_interpreter:execute_code:128 - text_to_gpt: ["[stdout]\nCurrent Working Directory: /home/zyx/A-Projects/Graduation/embedding/opencode/test_case/o4\nsys.path: ['/home/zyx/anaconda3/envs/base1/lib/python310.zip', '/home/zyx/anaconda3/envs/base1/lib/python3.10', '/home/zyx/anaconda3/envs/base1/lib/python3.10/lib-dynload', '', '/home/zyx/anaconda3/envs/base1/lib/python3.10/site-packages', '/home/zyx/A-Projects/owl']\n"]
2025-05-30 22:32:51.626 | INFO     | utils.local_interpreter:initialize:33 - 初始化本地内核
2025-05-30 22:32:52.454 | INFO     | utils.local_interpreter:execute_code_:141 - 执行代码: import os
work_dir = r'./'
os.makedirs(work_dir, exist_ok=True)
os.chdir(work_dir)
print('当前工作目录:', os.getcwd())
import matplotlib.pyplot as plt
import matplotlib as mpl
plt.rcParams['font.sans-serif'] = ['Arial Unicode MS', 'SimHei', 'Microsoft YaHei', 'WenQuanYi Micro Hei', 'PingFang SC', 'Hiragino Sans GB', 'Heiti SC', 'DejaVu Sans', 'sans-serif']
plt.rcParams['axes.unicode_minus'] = False
plt.rcParams['font.family'] = 'sans-serif'
mpl.rcParams['font.size'] = 12
mpl.rcParams['axes.labelsize'] = 12
mpl.rcParams['xtick.labelsize'] = 10
mpl.rcParams['ytick.labelsize'] = 10

2025-05-30 22:32:55.181 | INFO     | utils.local_interpreter:execute_code:61 - 执行代码: from api import gpt_chat
2025-05-30 22:32:55.184 | INFO     | utils.local_interpreter:execute_code:75 - 开始在本地执行代码...
2025-05-30 22:32:55.185 | INFO     | utils.local_interpreter:execute_code_:141 - 执行代码: from api import gpt_chat
2025-05-30 22:32:55.361 | INFO     | utils.local_interpreter:execute_code:78 - 代码执行完成，开始处理结果...
2025-05-30 22:32:55.362 | ERROR    | utils.local_interpreter:execute_code:122 - 执行错误: ---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[2], line 1
----> 1 from api import gpt_chat

ModuleNotFoundError: No module named 'api'
2025-05-30 22:32:55.365 | INFO     | utils.local_interpreter:execute_code:128 - text_to_gpt: ["---------------------------------------------------------------------------\nModuleNotFoundError                       Traceback (most recent call last)\nCell In[2], line 1\n----> 1 from api import gpt_chat\n\nModuleNotFoundError: No module named 'api'"]
2025-05-30 22:33:02.871 | INFO     | utils.local_interpreter:execute_code:61 - 执行代码: 
import os, sys
print("Current Working Directory:", os.getcwd())
print("sys.path:", sys.path)

2025-05-30 22:33:02.874 | INFO     | utils.local_interpreter:execute_code:75 - 开始在本地执行代码...
2025-05-30 22:33:02.875 | INFO     | utils.local_interpreter:execute_code_:141 - 执行代码: 
import os, sys
print("Current Working Directory:", os.getcwd())
print("sys.path:", sys.path)

2025-05-30 22:33:02.883 | INFO     | utils.local_interpreter:execute_code:78 - 代码执行完成，开始处理结果...
2025-05-30 22:33:02.892 | INFO     | utils.local_interpreter:execute_code:128 - text_to_gpt: ["[stdout]\nCurrent Working Directory: /home/zyx/A-Projects/Graduation/embedding/opencode\nsys.path: ['/home/zyx/anaconda3/envs/base1/lib/python310.zip', '/home/zyx/anaconda3/envs/base1/lib/python3.10', '/home/zyx/anaconda3/envs/base1/lib/python3.10/lib-dynload', '', '/home/zyx/anaconda3/envs/base1/lib/python3.10/site-packages', '/home/zyx/A-Projects/owl']\n"]
2025-05-30 22:33:23.523 | INFO     | utils.local_interpreter:execute_code:61 - 执行代码: from utils.api import gpt_chat
2025-05-30 22:33:23.528 | INFO     | utils.local_interpreter:execute_code:75 - 开始在本地执行代码...
2025-05-30 22:33:23.529 | INFO     | utils.local_interpreter:execute_code_:141 - 执行代码: from utils.api import gpt_chat
2025-05-30 22:33:23.918 | INFO     | utils.local_interpreter:execute_code:78 - 代码执行完成，开始处理结果...
2025-05-30 22:33:23.919 | INFO     | utils.local_interpreter:execute_code:128 - text_to_gpt: []
